name: Generate Poem and Post as Comment

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  generate-poem-and-comment:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install transformers torch PyGithub

      # Step 4: Generate poem and post as comment
      - name: Generate Poem and Post as Comment
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use GitHub secret
        run: |
          python .github/scripts/generate_poem.py
